### ISSUE TITLE
For consistency for education, LEDs should be controlled by variables

### ISSUE THREAD

**Issue by stephanemagnenat** [Mobsya/aseba-target-thymio2#28]
Currently in Thymio's firmware, almost sensor/actuator operations that deal with a value that persists over time are done with variables (e.g. motor, distance sensors), at the exception of LEDs. This creates a difference which does not correspond to any good theoretical reason, but rather reflects an implementation detail.

In an improved version of the robot, this should be made consistent, for the sake of easing explanations. Also, it would allow the users to change the value of LEDs through the variables in Studio, which would be very nice. Similarly, it would make it easier to have a real-time preview in VPL.

**Comment by davidjsherman** [comment]
This would also simply Scratch integration: it would remove the need for 9 of the "façade" functions in the [`thymio_motion.aesl` Natives](http://davidjsherman.github.io/inirobot-scratch-thymioII/aesl-doc/group___native.html) module. Not only Scratch, but any comtrol that goes through HTTP or Dbus.

**Comment by mbonani** [comment]
probably we can add this at least for the body colors of the Thymio, it could like sais help recent development

**Comment by mbonani** [comment]
After evaluating it seems reasonable to implement it on RGB led and on the circle led. The function will be kept in double for this led too. For the other leds it is better to keep the functions as the implies use of more memory and its inter-fear with the automatic behaviour of showing sensors activities.
