### ISSUE TITLE
Enforcing setting limits before saving

### ISSUE THREAD

**Issue by ypiguet-epfl** [Mobsya/aseba-target-thymio2#55]
In [behavior.c at line 487](/Mobsya/aseba-target-thymio2/blob/master/behavior.c#L487), `set_save_settings()` is called before constraining the new volume value between 0 and 8 inclusive. This causes a call to `AsebaNative__system_settings_flash()` at shutdown ([main.c line 295](/Mobsya/aseba-target-thymio2/blob/master/main.c#L295)) even if the volume hasn't been changed.

I suggest to move the tests as follows:
```
when(buttons_state[BUTTON_BACKWARD]) {
	if (volume < 8) {
		volume++;
		set_save_settings();
	}
}
when(buttons_state[BUTTON_FORWARD]) {
	if (volume > 0) {
		volume--;
		set_save_settings();
	}
}
```

There is the same problem with `SET_MOTOR` (`correction` between -50 and 50).

**Comment by mbonani** [comment]
implement in eb408bddabbfcca163cfc838a979c8c4d35e7d82
